### ISSUE TITLE
Update package on pub.dev

### ISSUE THREAD

**Issue by magginichi** [timestee/dart-webdav#18]
Can you update the package on pub.dev soon?

**Comment by timestee** [comment]
@magginichi ok  i will pub the latest version these days.

**Comment by avioli** [comment]
For anyone waiting... while waiting:

```yaml
  webdav: #^1.0.9
    git:
      url: https://github.com/timestee/dart-webdav.git
      ref: 1a70d3f7236484ed170f688980020b344d729d39
```
